"""
Streamlit entry point.

Day 1: simple RAG — retrieve chunks from ChromaDB, pass to Gemini, return answer.
Day 2: swap get_answer() for the full AgentExecutor.
Day 3: add ConversationBufferMemory.

Run with:  streamlit run app.py
"""

import streamlit as st
from dotenv import load_dotenv
load_dotenv()
from docagent.agent import build_agent
# ── UI ────────────────────────────────────────────────────────────────────────

st.set_page_config(page_title="DocAgent", page_icon="📄", layout="wide")
st.title("📄 DocAgent")
st.caption("LLM-powered Document Q&A — Day 1: RAG baseline")
@st.cache_resource
def get_agent():
    return build_agent()
agent = get_agent()

if st.button("Clear chat"):
    st.session_state.messages = []
    st.rerun()


# Keep conversation history in Streamlit session state
if "messages" not in st.session_state:
    st.session_state.messages = []

# Render previous messages
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

# Chat input
if question := st.chat_input("Ask something about the documents…"):
    # Show user message
    st.session_state.messages.append({"role": "user", "content": question})
    with st.chat_message("user"):
        st.markdown(question)

    # Get and show answer
    with st.chat_message("assistant"):
        with st.spinner("Retrieving and reasoning…"):
            answer = agent.invoke({"input": question}) ##agent.invoke() will call the agent's run() method, which will execute the agent's logic including tool calls, and return the final answer from Gemini after reasoning over the retrieved context and any tool outputs 
        st.markdown(answer['output']) ##answer is a dictionary containing the final output from the agent, which includes the answer generated by Gemini after processing the retrieved context and any tool outputs. We access the 'output' key to get the actual answer text to display in the chat interface.    

    st.session_state.messages.append({"role": "assistant", "content": answer["output"]})
